### ISSUE TITLE
Control 2 Easee chargers?

### ISSUE THREAD

**Issue by rabakaas** [elden1337/hass-peaq#322]
Is it possible to add a second chargers? I have added another Easee charger to my installation and want Peaqev to control both😃

**Comment by elden1337** [comment]
note to self, duplicates: #153

**Comment by elden1337** [comment]
@rabakaas if i would add support for multiple chargers (or ports in certain cases, like chargeamps aura), do you see that there should be a prioritization between the two?

- should one be considered primary and the other one secondary?
- should the one where there has been less charge added (if both are connected) be prioritized?
etc.

I'd like your thoughts on these and possibly other parameters since adding a secondary can be everything from just allowing multiple installations (with their own threshold then) to actually store and prioritize based on x factors.

**Comment by rabakaas** [comment]
Prioritization between the two is not a problem for me, but maybe for other users. If i need to charge one car rapidly I will simply plug in just that car. 
My Easee chargers are on the same circuit with one charger as master, maybe a possible solution can be replacing dynamic_charger_limt with dynamic_circuit_limit on the master charger? And max_charger_limit with max_circuit_limit, current with circuit_current. Then only the master charger need to be controlled by Peaqev.
